# Generated by Django 2.1.7 on 2019-03-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_playinggame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playinggame',
            name='hero1',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero10',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero2',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero3',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero4',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero5',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero6',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero7',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero8',
        ),
        migrations.RemoveField(
            model_name='playinggame',
            name='hero9',
        ),
    ]
