# Generated by Django 2.1.7 on 2019-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20190419_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='rank',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='hero',
            name='sigma',
            field=models.FloatField(default=8.333),
        ),
    ]
